import { Exclude } from 'class-transformer';
import { Column, Entity, PrimaryGeneratedColumn, ManyToOne } from 'typeorm';
import { TaskStatus } from './task-status.enum';

import { User } from 'src/auth/user.entity';

@Entity()
class Task {
  // This column is automatically generated by the database with a UUID
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  title: string;

  @Column()
  description: string;

  @Column()
  status: TaskStatus;

  // Many to one relationship
  // Many tasks can belong to one user
  // eager: false means that the tasks will not be loaded automatically when the user is loaded
  @ManyToOne((_type) => User, (user) => user.tasks, { eager: false })
  // toPlainOnly: true means that the user will not be included in the plain object when the task is serialized to JSON
  @Exclude({ toPlainOnly: true })
  user: User;
}

export { Task };
